# VECTIS developer task runner.
# Cross-platform: the python/npm targets run on the host; `up`/`down` use Docker.

.DEFAULT_GOAL := help
PY := python
BACKEND := backend
FRONTEND := frontend

.PHONY: help
help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-12s\033[0m %s\n", $$1, $$2}'

.PHONY: install
install: ## Install backend (editable, with dev extras) and frontend deps
	cd $(BACKEND) && $(PY) -m pip install -e ".[dev]"
	cd $(FRONTEND) && npm install

.PHONY: migrate
migrate: ## Apply database migrations (alembic upgrade head)
	cd $(BACKEND) && alembic upgrade head

.PHONY: revision
revision: ## Create a new autogenerated migration: make revision m="message"
	cd $(BACKEND) && alembic revision --autogenerate -m "$(m)"

.PHONY: seed
seed: ## Generate the deterministic Liguria sample dataset
	cd $(BACKEND) && $(PY) -m vectis.scripts.generate_sample

.PHONY: demo
demo: ## Run one end-to-end analysis and print the Decision Report (no API key needed)
	cd $(BACKEND) && $(PY) -m vectis.scripts.demo

.PHONY: demo-v2
demo-v2: ## Run the V2 end-to-end Liguria wildfire intelligence demo (offline, no API key)
	cd $(BACKEND) && $(PY) -m vectis.scripts.demo_v2

.PHONY: stress
stress: ## Run the 1,000,000-scenario Monte Carlo stress test (serial vs parallel, honest verdict)
	cd $(BACKEND) && $(PY) scripts/stress_test.py

.PHONY: storm
storm: ## Run the global-storm tiering stress test (thousands of cells crossing at once, honest numbers)
	cd $(BACKEND) && pytest -m slow tests/realtime/test_tiering_storm.py -s

.PHONY: train
train: ## Train + evaluate models on the sample and write the model card
	cd $(BACKEND) && $(PY) -m vectis.scripts.train

.PHONY: api
api: ## Run the FastAPI dev server on :8000
	cd $(BACKEND) && uvicorn vectis.api.main:app --reload --host 0.0.0.0 --port 8000

.PHONY: test
test: ## Run the backend test suite
	cd $(BACKEND) && pytest

.PHONY: lint
lint: ## Lint + type-check backend and frontend
	cd $(BACKEND) && ruff check . && mypy vectis
	cd $(FRONTEND) && npm run lint

.PHONY: format
format: ## Auto-format backend
	cd $(BACKEND) && ruff format . && ruff check --fix .

.PHONY: up
up: ## Start the full stack (db + backend + frontend) via docker-compose
	docker compose up --build

.PHONY: down
down: ## Stop the stack and remove volumes
	docker compose down -v
